# Generated by Django 2.2.3 on 2020-11-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego1App', '0002_auto_20201028_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=35)),
                ('accion', models.CharField(max_length=50)),
                ('numero_accion', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='participante',
            old_name='created',
            new_name='creado',
        ),
        migrations.AddField(
            model_name='participante',
            name='contacto',
            field=models.CharField(default='No', max_length=50),
            preserve_default=False,
        ),
    ]
