# Generated by Django 2.2.3 on 2020-11-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego1App', '0003_auto_20201101_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='nombre',
            field=models.CharField(max_length=55),
        ),
    ]
